#!/bin/bash

# Gather System Information
hostname=$(hostname)
os=$(source /etc/os-release && echo $name)
uptime=$(uptime -p)

# Gather Hardware Information
cpu=$(sudo lshw -class processor | grep "product" | head -1)
ram=$(free -h | grep Mem | awk '{print $2}')
disks=$(lsblk -d | awk '{print $1, $4}')
video=$(sudo lshw -class display | grep "product")

# Gather Network Information
ip=$(hostname -I | awk '{print $1}')
gateway=$(ip r | grep default | awk '{print $3}')
dns=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')
fqdn=$(hostname -f)

# Gather System Status
users=$(who | awk '{print $1}' | sort | uniq)
disk_space=$(df -h)
process_count=$(ps -e | wc -l)
load_average=$(uptime | awk -F'[a-z]:' '{ print $2}')
memory_allocation=$(free -h)
listening_ports=$(ss -tulwn | grep LISTEN)
ufw_rules=$(sudo ufw status verbose)

# Print Report

echo "
---------------------------------------------------------------------------------------------------------------------------------------------------------
System Report generated by $users, $(date)

System Information
------------------
Hostname: $hostname
OS: $os
Uptime: $uptime

Hardware Information
--------------------------------------------------------------------------------------------------------------------------------------
$cpu
Ram: $ram
Disk(s): $disks
Video: $video

Network Information
--------------------------------------------------------------------------------------------------------------------------------
FQDN: $fqdn
Host Address: $ip
Gateway IP: $gateway
DNS Server: $dns

System Status
------------------------------------------------------------------------------------------------------------
Users Logged In: $users
Disk Space: 
$disk_space
Process Count: $process_count
Load Averages: $load_average
Memory Allocation: 
$memory_allocation
Listening Network Ports: 
$listening_ports
UFW Rules: 
$ufw_rules
---------------------------------------------------------------------------------------------------------------
"
