shrey@Generic-VM:~/Linux-Automation$ sudo bash Assignment2.sh
[sudo] password for shrey: 
#############################################
## Updating Network Configuration
#############################################

** (generate:2576): WARNING **: 18:40:47.375: Permissions for /etc/netplan/01-netcfg.yaml are too open. Netplan configuration should NOT be accessible by others.

** (generate:2576): WARNING **: 18:40:47.376: `gateway4` has been deprecated, use default routes instead.
See the 'Default routes' section of the documentation for more details.

** (generate:2576): WARNING **: 18:40:47.376: Permissions for /etc/netplan/01-network-manager-all.yaml are too open. Netplan configuration should NOT be accessible by others.

** (process:2574): WARNING **: 18:40:47.920: Permissions for /etc/netplan/01-netcfg.yaml are too open. Netplan configuration should NOT be accessible by others.

** (process:2574): WARNING **: 18:40:47.920: `gateway4` has been deprecated, use default routes instead.
See the 'Default routes' section of the documentation for more details.

** (process:2574): WARNING **: 18:40:47.920: Permissions for /etc/netplan/01-network-manager-all.yaml are too open. Netplan configuration should NOT be accessible by others.

** (process:2574): WARNING **: 18:40:48.289: Permissions for /etc/netplan/01-netcfg.yaml are too open. Netplan configuration should NOT be accessible by others.

** (process:2574): WARNING **: 18:40:48.290: `gateway4` has been deprecated, use default routes instead.
See the 'Default routes' section of the documentation for more details.

** (process:2574): WARNING **: 18:40:48.290: Permissions for /etc/netplan/01-network-manager-all.yaml are too open. Netplan configuration should NOT be accessible by others.

** (process:2574): WARNING **: 18:40:48.290: Permissions for /etc/netplan/01-netcfg.yaml are too open. Netplan configuration should NOT be accessible by others.

** (process:2574): WARNING **: 18:40:48.290: `gateway4` has been deprecated, use default routes instead.
See the 'Default routes' section of the documentation for more details.

** (process:2574): WARNING **: 18:40:48.290: Permissions for /etc/netplan/01-network-manager-all.yaml are too open. Netplan configuration should NOT be accessible by others.
#############################################
## Updating /etc/hosts file
#############################################
#############################################
## Installing Required Packages
#############################################
INFO: Installing apache2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  apache2-bin apache2-data apache2-utils libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap
Suggested packages:
  apache2-doc apache2-suexec-pristine | apache2-suexec-custom
The following NEW packages will be installed:
  apache2 apache2-bin apache2-data apache2-utils libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap
0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,919 kB of archives.
After this operation, 7,718 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libapr1 amd64 1.7.0-8ubuntu0.22.04.1 [108 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libaprutil1 amd64 1.6.1-5ubuntu4.22.04.2 [92.8 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libaprutil1-dbd-sqlite3 amd64 1.6.1-5ubuntu4.22.04.2 [11.3 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libaprutil1-ldap amd64 1.6.1-5ubuntu4.22.04.2 [9,170 B]
Get:5 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 apache2-bin amd64 2.4.52-1ubuntu4.7 [1,346 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 apache2-data all 2.4.52-1ubuntu4.7 [165 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 apache2-utils amd64 2.4.52-1ubuntu4.7 [88.8 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 apache2 amd64 2.4.52-1ubuntu4.7 [97.8 kB]
Fetched 1,919 kB in 1s (2,812 kB/s)
Selecting previously unselected package libapr1:amd64.
(Reading database ... 207144 files and directories currently installed.)
Preparing to unpack .../0-libapr1_1.7.0-8ubuntu0.22.04.1_amd64.deb ...
Unpacking libapr1:amd64 (1.7.0-8ubuntu0.22.04.1) ...
Selecting previously unselected package libaprutil1:amd64.
Preparing to unpack .../1-libaprutil1_1.6.1-5ubuntu4.22.04.2_amd64.deb ...
Unpacking libaprutil1:amd64 (1.6.1-5ubuntu4.22.04.2) ...
Selecting previously unselected package libaprutil1-dbd-sqlite3:amd64.
Preparing to unpack .../2-libaprutil1-dbd-sqlite3_1.6.1-5ubuntu4.22.04.2_amd64.deb ...
Unpacking libaprutil1-dbd-sqlite3:amd64 (1.6.1-5ubuntu4.22.04.2) ...
Selecting previously unselected package libaprutil1-ldap:amd64.
Preparing to unpack .../3-libaprutil1-ldap_1.6.1-5ubuntu4.22.04.2_amd64.deb ...
Unpacking libaprutil1-ldap:amd64 (1.6.1-5ubuntu4.22.04.2) ...
Selecting previously unselected package apache2-bin.
Preparing to unpack .../4-apache2-bin_2.4.52-1ubuntu4.7_amd64.deb ...
Unpacking apache2-bin (2.4.52-1ubuntu4.7) ...
Selecting previously unselected package apache2-data.
Preparing to unpack .../5-apache2-data_2.4.52-1ubuntu4.7_all.deb ...
Unpacking apache2-data (2.4.52-1ubuntu4.7) ...
Selecting previously unselected package apache2-utils.
Preparing to unpack .../6-apache2-utils_2.4.52-1ubuntu4.7_amd64.deb ...
Unpacking apache2-utils (2.4.52-1ubuntu4.7) ...
Selecting previously unselected package apache2.
Preparing to unpack .../7-apache2_2.4.52-1ubuntu4.7_amd64.deb ...
Unpacking apache2 (2.4.52-1ubuntu4.7) ...
Setting up libapr1:amd64 (1.7.0-8ubuntu0.22.04.1) ...
Setting up apache2-data (2.4.52-1ubuntu4.7) ...
Setting up libaprutil1:amd64 (1.6.1-5ubuntu4.22.04.2) ...
Setting up libaprutil1-ldap:amd64 (1.6.1-5ubuntu4.22.04.2) ...
Setting up libaprutil1-dbd-sqlite3:amd64 (1.6.1-5ubuntu4.22.04.2) ...
Setting up apache2-utils (2.4.52-1ubuntu4.7) ...
Setting up apache2-bin (2.4.52-1ubuntu4.7) ...
Setting up apache2 (2.4.52-1ubuntu4.7) ...
Enabling module mpm_event.
Enabling module authz_core.
Enabling module authz_host.
Enabling module authn_core.
Enabling module auth_basic.
Enabling module access_compat.
Enabling module authn_file.
Enabling module authz_user.
Enabling module alias.
Enabling module dir.
Enabling module autoindex.
Enabling module env.
Enabling module mime.
Enabling module negotiation.
Enabling module setenvif.
Enabling module filter.
Enabling module deflate.
Enabling module status.
Enabling module reqtimeout.
Enabling conf charset.
Enabling conf localized-error-pages.
Enabling conf other-vhosts-access-log.
Enabling conf security.
Enabling conf serve-cgi-bin.
Enabling site 000-default.
Created symlink /etc/systemd/system/multi-user.target.wants/apache2.service → /lib/systemd/system/apache2.service.
Created symlink /etc/systemd/system/multi-user.target.wants/apache-htcacheclean.service → /lib/systemd/system/apache-htcacheclean.service.
Processing triggers for ufw (0.36.1-4ubuntu0.1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.6) ...
INFO: squid is already installed
#############################################
## Configuring Firewall
#############################################
Backing up 'user.rules' to '/etc/ufw/user.rules.20240314_184102'
Backing up 'before.rules' to '/etc/ufw/before.rules.20240314_184102'
Backing up 'after.rules' to '/etc/ufw/after.rules.20240314_184102'
Backing up 'user6.rules' to '/etc/ufw/user6.rules.20240314_184102'
Backing up 'before6.rules' to '/etc/ufw/before6.rules.20240314_184102'
Backing up 'after6.rules' to '/etc/ufw/after6.rules.20240314_184102'

Default incoming policy changed to 'deny'
(be sure to update your rules accordingly)
Default outgoing policy changed to 'allow'
(be sure to update your rules accordingly)
Rules updated
Rules updated (v6)
Rules updated
Rules updated (v6)
Rules updated
Firewall is active and enabled on system startup
#############################################
## Creating User Accounts
#############################################
INFO: Creating user dennis
Adding user `dennis' ...
Adding new group `dennis' (1001) ...
Adding new user `dennis' (1001) with group `dennis' ...
Creating home directory `/home/dennis' ...
Copying files from `/etc/skel' ...
cp: cannot stat '/root/.ssh/authorized_keys': No such file or directory
chmod: cannot access '/home/dennis/.ssh/authorized_keys': No such file or directory
INFO: Creating user aubrey
Adding user `aubrey' ...
Adding new group `aubrey' (1002) ...
Adding new user `aubrey' (1002) with group `aubrey' ...
Creating home directory `/home/aubrey' ...
Copying files from `/etc/skel' ...
cp: cannot stat '/root/.ssh/authorized_keys': No such file or directory
chmod: cannot access '/home/aubrey/.ssh/authorized_keys': No such file or directory
INFO: Creating user captain
Adding user `captain' ...
Adding new group `captain' (1003) ...
Adding new user `captain' (1003) with group `captain' ...
Creating home directory `/home/captain' ...
Copying files from `/etc/skel' ...
cp: cannot stat '/root/.ssh/authorized_keys': No such file or directory
chmod: cannot access '/home/captain/.ssh/authorized_keys': No such file or directory
INFO: Creating user snibbles
Adding user `snibbles' ...
Adding new group `snibbles' (1004) ...
Adding new user `snibbles' (1004) with group `snibbles' ...
Creating home directory `/home/snibbles' ...
Copying files from `/etc/skel' ...
cp: cannot stat '/root/.ssh/authorized_keys': No such file or directory
chmod: cannot access '/home/snibbles/.ssh/authorized_keys': No such file or directory
INFO: Creating user brownie
Adding user `brownie' ...
Adding new group `brownie' (1005) ...
Adding new user `brownie' (1005) with group `brownie' ...
Creating home directory `/home/brownie' ...
Copying files from `/etc/skel' ...
cp: cannot stat '/root/.ssh/authorized_keys': No such file or directory
chmod: cannot access '/home/brownie/.ssh/authorized_keys': No such file or directory
INFO: Creating user scooter
Adding user `scooter' ...
Adding new group `scooter' (1006) ...
Adding new user `scooter' (1006) with group `scooter' ...
Creating home directory `/home/scooter' ...
Copying files from `/etc/skel' ...
cp: cannot stat '/root/.ssh/authorized_keys': No such file or directory
chmod: cannot access '/home/scooter/.ssh/authorized_keys': No such file or directory
INFO: Creating user sandy
Adding user `sandy' ...
Adding new group `sandy' (1007) ...
Adding new user `sandy' (1007) with group `sandy' ...
Creating home directory `/home/sandy' ...
Copying files from `/etc/skel' ...
cp: cannot stat '/root/.ssh/authorized_keys': No such file or directory
chmod: cannot access '/home/sandy/.ssh/authorized_keys': No such file or directory
INFO: Creating user perrier
Adding user `perrier' ...
Adding new group `perrier' (1008) ...
Adding new user `perrier' (1008) with group `perrier' ...
Creating home directory `/home/perrier' ...
Copying files from `/etc/skel' ...
cp: cannot stat '/root/.ssh/authorized_keys': No such file or directory
chmod: cannot access '/home/perrier/.ssh/authorized_keys': No such file or directory
INFO: Creating user cindy
Adding user `cindy' ...
Adding new group `cindy' (1009) ...
Adding new user `cindy' (1009) with group `cindy' ...
Creating home directory `/home/cindy' ...
Copying files from `/etc/skel' ...
cp: cannot stat '/root/.ssh/authorized_keys': No such file or directory
chmod: cannot access '/home/cindy/.ssh/authorized_keys': No such file or directory
INFO: Creating user tiger
Adding user `tiger' ...
Adding new group `tiger' (1010) ...
Adding new user `tiger' (1010) with group `tiger' ...
Creating home directory `/home/tiger' ...
Copying files from `/etc/skel' ...
cp: cannot stat '/root/.ssh/authorized_keys': No such file or directory
chmod: cannot access '/home/tiger/.ssh/authorized_keys': No such file or directory
INFO: Creating user yoda
Adding user `yoda' ...
Adding new group `yoda' (1011) ...
Adding new user `yoda' (1011) with group `yoda' ...
Creating home directory `/home/yoda' ...
Copying files from `/etc/skel' ...
cp: cannot stat '/root/.ssh/authorized_keys': No such file or directory
chmod: cannot access '/home/yoda/.ssh/authorized_keys': No such file or directory
