#!/bin/bash

# System Information
HOSTNAME=$(hostname)
DATE=$(date)
OS=$(source /etc/os-release && echo $PRETTY_NAME)
UPTIME=$(uptime -p)

# Hardware Information
CPU_INFO=$(lshw -class processor | awk '/product/ {print $2" "$3" "$4}')
CPU_SPEED=$(lshw -class processor | awk '/capacity/ {print $2}')
MAX_CPU_SPEED=$(lscpu | awk '/^CPU MHz/ {print $3}')
RAM=$(free -h | awk '/Mem:/ {print $2}')
DISKS=$(lsblk -io NAME,MODEL,SIZE | grep -v 'NAME')
VIDEO=$(lspci | grep -i vga | awk -F': ' '{print $3}')

# Network Information
FQDN=$(hostname -f)
HOST_IP=$(hostname -I)
GATEWAY=$(ip r | awk '/default/ {print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | awk '/nameserver/ {print $2}')
NETWORK_INTERFACE=$(ip -o -4 addr show | awk '!/^[0-9]*: ?lo|link\/ether/ {print $2,$3}')
INTERFACE_NAME=$(echo $NETWORK_INTERFACE | awk '{print $1}')
INTERFACE_IP=$(echo $NETWORK_INTERFACE | awk '{print $2}')

# System Status
USERS=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',')
DISK_SPACE=$(df -h | awk '{print $6,$4}' | sed '1d')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(cat /proc/loadavg | awk '{print $1",",$2",",$3}')
MEMORY_ALLOC=$(free -h | awk '/Mem:/ {print $3}')
LISTENING_PORTS=$(ss -tuln | awk 'NR>1 {print $5}' | cut -d':' -f2 | sort | uniq | tr '\n' ',')
UFW_RULES=$(sudo ufw status | awk 'NR>5 {print $0}')

# Output
echo "
System Report generated by $(whoami), $DATE

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU_INFO
Speed: $CPU_SPEED (max: $MAX_CPU_SPEED)
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_IP
Gateway IP: $GATEWAY
DNS Server: $DNS_SERVER

Interface Name: $INTERFACE_NAME
IP Address: $INTERFACE_IP

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation: $MEMORY_ALLOC
Listening Network Ports: $LISTENING_PORTS
UFW Rules: $UFW_RULES
"
